unit_tests:
  image: node:12.10.0
  stage: test
  before_script:
    - npm install
  script:
    - npm run test:ci

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - yarn
    - yarn run build
    - firebase use marvel-cdb --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN