image: node:12.10.0
unit_tests:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test:ci

deploy-prod:
  
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm install -g firebase
    - npm run build
    - firebase use marvel-cdb --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
